from __future__ import annotations

import json
import subprocess
import sys
import unittest
from pathlib import Path

import mido


def _run_cli(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "aimusic.app.cli", *args],
        capture_output=True,
        text=True,
    )


class TestCliGenerateInspectExportWorkflow(unittest.TestCase):
    """Exercises generate -> inspect -> export -> MIDI load as one regression."""

    def setUp(self) -> None:
        self._tmp = self._make_tmp_dir()

    def _make_tmp_dir(self) -> Path:
        import tempfile

        self._tmp_ctx = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp_ctx.cleanup)
        return Path(self._tmp_ctx.name)

    def _generate(self, seed: int = 7, beats: int = 4) -> tuple[Path, Path, Path]:
        result = _run_cli(
            "generate",
            "--seed", str(seed),
            "--beats", str(beats),
            "--out", str(self._tmp),
        )
        self.assertEqual(result.returncode, 0, msg=result.stderr)

        score_paths = sorted(self._tmp.glob("*_score.json"))
        midi_paths = sorted(self._tmp.glob("*.mid"))
        manifest_paths = sorted(self._tmp.glob("*_manifest.json"))
        self.assertEqual(len(score_paths), 1)
        self.assertEqual(len(midi_paths), 1)
        self.assertEqual(len(manifest_paths), 1)
        return score_paths[0], midi_paths[0], manifest_paths[0]

    def test_generate_creates_score_midi_and_manifest(self) -> None:
        score_path, midi_path, manifest_path = self._generate()

        score_data = json.loads(score_path.read_text(encoding="utf-8"))
        self.assertIn("note_events", score_data)
        self.assertGreater(score_data["event_count"], 0)

        # MIDI file generated by `generate` must itself be loadable.
        mido.MidiFile(str(midi_path))

        manifest_data = json.loads(manifest_path.read_text(encoding="utf-8"))
        self.assertIn("structure", manifest_data)
        self.assertIn("sb_stats", manifest_data)

    def test_inspect_reads_manifest_structure_key_and_prints_tension_arc(self) -> None:
        _, _, manifest_path = self._generate()

        result = _run_cli("inspect", str(manifest_path))

        self.assertEqual(result.returncode, 0, msg=result.stderr)
        self.assertIn("Schrödinger Bridge Health", result.stdout)
        self.assertIn("Graph Candidate Flow", result.stdout)
        self.assertIn("Graph Edge Flow", result.stdout)
        self.assertIn("Original support", result.stdout)
        self.assertIn("Residual history", result.stdout)
        self.assertIn("Entropy by layer", result.stdout)
        self.assertIn("Final Path Selection", result.stdout)
        self.assertIn("Key Timeline", result.stdout)
        self.assertIn("Chord Timeline", result.stdout)
        self.assertIn("Role Timeline", result.stdout)
        self.assertIn("Groove Timeline", result.stdout)
        self.assertIn("Boundaries", result.stdout)
        self.assertIn("Tension Arc", result.stdout)
        # Regression guard: previously read the wrong key and always printed
        # empty/absent timelines and an empty tension arc.
        self.assertNotIn("(no segments)", result.stdout)
        self.assertRegex(result.stdout, r"Beat \d+\.\d: ")

    def test_inspect_tension_values_are_rounded_not_raw_floats(self) -> None:
        _, _, manifest_path = self._generate()

        result = _run_cli("inspect", str(manifest_path))

        self.assertEqual(result.returncode, 0, msg=result.stderr)
        # Tension values must render as fixed 3-decimal numbers, never the
        # long floating-point artifacts (e.g. 0.35000000000000003).
        for line in result.stdout.splitlines():
            if line.startswith("Beat "):
                self.assertRegex(line, r"\(\d\.\d{3}\)$", msg=line)

    def test_export_renders_generated_score_without_modification(self) -> None:
        score_path, _, _ = self._generate()
        export_path = self._tmp / "reexported.mid"

        result = _run_cli("export", str(score_path), "--out", str(export_path))

        self.assertEqual(result.returncode, 0, msg=result.stderr)
        self.assertTrue(export_path.exists())

        midi = mido.MidiFile(str(export_path))
        note_ons = [
            msg for track in midi.tracks for msg in track
            if msg.type == "note_on" and msg.velocity > 0
        ]
        self.assertGreater(len(note_ons), 0)

    def test_inspect_on_missing_file_exits_nonzero_with_actionable_message(self) -> None:
        result = _run_cli("inspect", str(self._tmp / "does_not_exist_manifest.json"))

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("Could not find manifest", result.stdout)

    def test_inspect_on_malformed_json_exits_nonzero_with_actionable_message(self) -> None:
        bad_path = self._tmp / "bad_manifest.json"
        bad_path.write_text("{not valid json", encoding="utf-8")

        result = _run_cli("inspect", str(bad_path))

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("not valid JSON", result.stdout)

    def test_inspect_on_manifest_missing_required_fields_exits_nonzero(self) -> None:
        incomplete_path = self._tmp / "incomplete_manifest.json"
        incomplete_path.write_text(json.dumps({"run_id": "abc"}), encoding="utf-8")

        result = _run_cli("inspect", str(incomplete_path))

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("missing field", result.stdout)

    def test_export_on_incompatible_score_payload_exits_nonzero(self) -> None:
        bad_score_path = self._tmp / "bad_score.json"
        bad_score_path.write_text(json.dumps({"note_events": [{"ton": 0}]}), encoding="utf-8")

        result = _run_cli("export", str(bad_score_path))

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("not a valid score file", result.stdout)

    def test_export_on_missing_score_file_exits_nonzero(self) -> None:
        result = _run_cli("export", str(self._tmp / "does_not_exist_score.json"))

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("Could not find score file", result.stdout)

    def test_full_generate_inspect_export_midi_load_regression(self) -> None:
        score_path, midi_path, manifest_path = self._generate(seed=11, beats=6)

        inspect_result = _run_cli("inspect", str(manifest_path))
        self.assertEqual(inspect_result.returncode, 0, msg=inspect_result.stderr)

        export_path = self._tmp / "regression_export.mid"
        export_result = _run_cli("export", str(score_path), "--out", str(export_path))
        self.assertEqual(export_result.returncode, 0, msg=export_result.stderr)

        # Both the originally generated MIDI and the re-exported MIDI must load.
        original_midi = mido.MidiFile(str(midi_path))
        reexported_midi = mido.MidiFile(str(export_path))
        self.assertGreaterEqual(len(original_midi.tracks), 1)
        self.assertGreaterEqual(len(reexported_midi.tracks), 1)


if __name__ == "__main__":
    unittest.main()
